version: '3'
services:
  apache:
    build: apache
    ports:
      - "80:80"
    networks:
      my_network:
        ipv4_address: 192.168.46.50
        aliases:
          - exemplo.lan
          - www.exemplo.lan
          - eq1.exemplo.lan      
          - web2.exemplo.lan
    volumes:
      - ./exemplo.lan/:/opt/web/exemplo.lan/
      - ./apache/tarefa2.conf:/etc/apache2/sites-enabled/apache2.conf

  cliente:
    hostname: cliente
    build: cliente
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix    
    networks:
      my_network:    
        ipv4_address: 192.168.46.100


networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.46.0/24